require 'rake/clean'

desc "Run the Haskell-lib tests"
task :test do
  sh "ghc --make PrimesTest"
  sh "PrimesTest"
end

SRC = FileList['*.hs']
CLEAN.include('*.hi', '*.o')
CLOBBER.include("PrimesTest")
