require 'rake/clean'

desc "Run the Haskell-lib tests"
task :test do
  sh "ghc --make -O2 NumbersTest"
  sh "NumbersTest"
end

desc "start ghci"
task :ghci do
  sh "ghci Numbers.hs"
end

SRC = FileList['*.hs']
CLEAN.include('*.hi', '*.o')
CLOBBER.include("NumbersTest")
