require 'rake/clean'

desc "Run the Haskell-lib tests"
task :test do
  sh "ghc --make NumbersTest"
  sh "NumbersTest"
end

SRC = FileList['*.hs']
CLEAN.include('*.hi', '*.o')
CLOBBER.include("NumbersTest")
